UPDATE dbo.FactSponsorship
SET DateKey =
  CASE
    WHEN Quarter LIKE '%Q1%' THEN CONVERT(INT, CONVERT(CHAR(8), CAST(CONCAT(Year,'-01-01') AS DATE),112))
    WHEN Quarter LIKE '%Q2%' THEN CONVERT(INT, CONVERT(CHAR(8), CAST(CONCAT(Year,'-04-01') AS DATE),112))
    WHEN Quarter LIKE '%Q3%' THEN CONVERT(INT, CONVERT(CHAR(8), CAST(CONCAT(Year,'-07-01') AS DATE),112))
    WHEN Quarter LIKE '%Q4%' THEN CONVERT(INT, CONVERT(CHAR(8), CAST(CONCAT(Year,'-10-01') AS DATE),112))
    ELSE CONVERT(INT, CONVERT(CHAR(8), CAST(CONCAT(Year,'-01-01') AS DATE),112))
  END
WHERE DateKey IS NULL;
GO